image: maven:3.6.3

pipelines:
  custom:
    deploy-to-ec2:
      - step:
          script:
            - mvn clean install
          artifacts:
            - target/**
      - step:
          deployment: Test
          script:
            - docker build ./ -t $AWS_ECR_REPOSITORY
            - pipe: "atlassian/aws-ecr-push-image:1.1.0"
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $AWS_ECR_REPOSITORY
            - pipe: "atlassian/ssh-run:0.2.4"
              variables:
                SSH_USER: ubuntu
                SERVER: $SERVER_IP
                SSH_KEY: $SSH_KEY
                MODE: script
                COMMAND: deployment.sh
